RoboStack/ros-humble

patch/ros-humble-mimick-vendor.win.patch, vinca_win.yaml
Debug https://github.com/RoboStack/ros-humble/issues/28 .
=> Commit fixes to build mimick_vendor on Windows locally

README.md
@Nicogene and @martinaxgloria were installing ROS Humble on a aarch64 machine, and were not able to install the OpenGL packages. I tried to provide the info of which packages to install in the most minimal way possible to avoid confusing further "regular" x86_64 users, but any suggestions to improve this are welcome.
fyi @Tobias-Fischer
=> Specify which packages to install for OpenGL support on aarch64

vinca_linux_64.yaml
Adding these for `robostack-staging` Linux64
They existed in `robostack-humble` but not updated yet.
Build with boa and ran vinca-azure locally
=> added geodesy and geographic-info

vinca_osx.yaml
This PR adds the following ros2_controllers:
ackermann-steering-controller
admittance-controller
forward-command-controller
and it updates control_msgs
This PR is fixing https://github.com/RoboStack/ros-humble/issues/79 and supersedes #80 (as it targets the main branch)
=> Add ackermann, admittance and forward-command ros2_controllers for osx on main branch

vinca_osx.yaml
This PR adds three other controllers:
- bicycle_steering_controller
- diff_drive_controller
- effort_controllers
This PR is using the same approach than the previous PR only adding new packages.
=> Add 3 other controllers from ros2_controllers.

patch/ros-humble-google-benchmark-vendor.patch
vinca generated recipe ask for 
https://github.com/ros2-gbp/google_benchmark_vendor-release/blob/release/humble/google_benchmark_vendor/0.1.2-1/CMakeLists.txt#L15
which needs the updated patch files
=> Update ros-humble-google-benchmark-vendor.patch to reflect upstream change

patch/dependencies.yaml, patch/ros-humble-ament-package.patch
importlib.resource.files is only [available in python>3.9 ](https://docs.python.org/3/library/importlib.resources.html#importlib.resources.files).
So we fallback to use request_resource package when the `files` function isn't available.
=> add python38 compatbility to rebuilt_2024 branch

patch/ros-humble-ament-package.patch
The patch in #127 was problematic due to manually edited patch file
I have regenerated one and ensure my local built is successful. 
I've also migrated `get_isolated_prefix_level_template_path`.
=> fix a broken ros-humble-ament-package.patch 

patch/ros-humble-librealsense2.patch, vinca_linux_64.yaml
* patch  set FORCE_RSUSB_BACKEND=ON as default option to fix v4l2 incompatibility issue with conda sysroot.
* `FORCE_RSUSB_BACKEND` is the [recommended setting](https://dev.intelrealsense.com/docs/build-configuration#back-end-recommended-configuration) for windows/mac 
* `FORCE_RSUSB_BACKEND=ON` align with official realsense [conda-forge feedstock](https://github.com/conda-forge/librealsense-feedstock/blob/main/recipe/build.sh#L45).
* compiled binary tested working hardware (see below)
* PR targeted at rebuild_2024 instead of main as the conda_pinnings in main are too old to create build environment. On the contrary it work in rebuild_2024
```
FAILED: CMakeFiles/realsense2.dir/src/linux/backend-v4l2.cpp.o …
```
=> Add realsense support

.github/workflows/testpr.yml, .scripts/build_win.bat, patch/ros-humble-gazebo-ros2-control.patch, patch/ros-humble-hardware-interface.patch, vinca_win.yaml
Remove a regression of https://github.com/RoboStack/ros-humble/pull/141 .
=> Fix Windows build follow up and enable more Windows packages

patch/ros-humble-iceoryx-binding-c.win.patch, patch/ros-humble-iceoryx-dds.win.patch, patch/ros-humble-iceoryx-hoofs.win.patch, patch/ros-humble-iceoryx-posh.win.patch, vinca_win.yaml
Fix https://github.com/RoboStack/ros-humble/issues/151
=> Enable rmw_cyclonedds_cpp package on Windows

vinca_win.yaml
Follow up to https://github.com/RoboStack/ros-humble/pull/158, now the installation works fine on Linux but on Windows a package is still missing.
=> Add joint-state-publisher-gui to Windows packages

patch/ros-humble-rosidl-generator-py.patch
The initial problem for me was that when performing a full rebuild, it complains later about not finding `Python.h` (when generating or depending on some messages, I think). Some CMake-export file does not properly expose the Python dependency in a later stage.
The following patch worked a little bit better when doing a local rebuild, but the Python demos actually crash with a segfault on macOS... I haven't investigated why but I remember that such a crash was previously a problem when linking Python, right?
Just for reference I copied a bit of CMake from the current main branch: https://github.com/ros2/rosidl_python/blob/rolling/rosidl_generator_py/cmake/rosidl_generator_py_generate_interfaces.cmake
I can try to find some more minimal way of debugging this over the next days.
=> update ros idl generate-py patch

patch/ros-humble-libstatistics-collector.patch, patch/ros-humble-rosbag2-compression.patch, patch/ros-humble-rosidl-generator-py.patch
I had to make the linkage PRIVATE to work on Linux (and not complain later on).
And I had to add 2x `cstdint` header because `gcc 13` requires it.
=> add additional patches for gcc 13 and fix rosidl py generator patch on linux

robostack.yaml
Workaround for:
* https://github.com/RoboStack/ros-humble/issues/175
* https://github.com/conda-forge/gazebo-feedstock/issues/107
Similar to https://github.com/RoboStack/ros-noetic/pull/464 .
It will be only useful after a rebuild, but let's do it so it is there when we do a rebuild.
=> Inject libprotobuf and libabseil dependency if a package depends on Gazebo Classic

vinca_linux_64.yaml, vinca_linux_aarch64.yaml, vinca_osx.yaml, vinca_osx_arm64.yaml, vinca_win.yaml
Should fix https://github.com/prefix-dev/pixi/issues/1529
=> triggering build(s) to get the latest ros-humble-launch-testing

vinca_linux_64.yaml, vinca_linux_aarch64.yaml, vinca_osx.yaml, vinca_osx_arm64.yaml, vinca_win.yaml
Fix https://github.com/RoboStack/ros-humble/issues/234
Fix https://github.com/RoboStack/ros-humble/issues/227
Fix https://github.com/RoboStack/ros-humble/issues/222
=> Add Universal Robots packages with January 2025 rebuild

patch/dependencies.yaml, patch/ros-humble-grid-map-cv.patch, pixi.toml, vinca_linux_64.yaml
- Add package grid_map and its dependencies
- Fix channel missing build task in pixi.toml
=> Add grid_map and its dependencies

patch/ros-humble-lanelet2-core.patch, patch/ros-humble-lanelet2-examples.patch, patch/ros-humble-lanelet2-io.patch, patch/ros-humble-lanelet2-matching.patch, patch/ros-humble-lanelet2-projection.patch, patch/ros-humble-lanelet2-python.patch, patch/ros-humble-lanelet2-routing.patch, patch/ros-humble-lanelet2-traffic-rules.patch, patch/ros-humble-lanelet2-validation.patch, patch/ros-humble-mrt-cmake-modules.patch, pixi.lock, pixi.toml, vinca_linux_64.yaml, vinca_linux_aarch64.yaml, vinca_osx.yaml, vinca_osx_arm64.yaml, vinca_win.yaml
=> feat: add lanelet2

.github/workflows/testpr.yml, conda_build_config.yaml, pixi.lock, pixi.toml, pkg_additional_info.yaml, vinca_linux_64.yaml, vinca_linux_aarch64.yaml, vinca_osx.yaml, vinca_osx_arm64.yaml, vinca_win.yaml
@wep21 noticed that after the build in https://github.com/RoboStack/ros-humble/pull/242, the build `ros-humble-lanelet2-io` package uses pugixml 1.15, while rviz uses pugixml 1.14 . This was a consequence of us not using the conda-forge complete pinning file due to https://github.com/prefix-dev/rattler-build/discussions/1285, and a recent pugixml update https://github.com/conda-forge/pugixml-feedstock/pull/27 .
As only the `lanelet2-io` package is affected, the best solution is to just rebuild this package with the correct pugixml version, to permit these I done the modification in vinca proposed in https://github.com/RoboStack/vinca/pull/67 .
=> Rebuild lanelet2-io with correct pugixml and ros-humble-ros-workspace with fastrtps fix

.github/workflows/testpr.yml, pixi.lock, pixi.toml
After https://github.blog/changelog/2025-01-16-linux-arm64-hosted-runners-now-available-for-free-in-public-repositories-public-preview/ we can use GitHub Actions also for native builds on `linux-aarch64`.
=> Switch linux-aarch64 to use public ubuntu-24.04-arm

conda_build_config.yaml, patch/dependencies.yaml, patch/ros-humble-zenoh-cpp-vendor.patch, robostack.yaml, vinca_linux_64.yaml, vinca_linux_aarch64.yaml, vinca_osx.yaml, vinca_osx_arm64.yaml, vinca_win.yaml
Fix https://github.com/RoboStack/ros-humble/issues/252 .
fyi @wep21
=>  Add rmw_zenoh_cpp and de-vendor zenoh_cpp_vendor 

patch/ros-humble-ur-client-library.osx.patch, vinca_osx.yaml, vinca_osx_arm64.yaml
=> feat: remove ur skip for osx

vinca_linux_64.yaml, vinca_linux_aarch64.yaml, vinca_osx.yaml, vinca_osx_arm64.yaml, vinca_win.yaml
Adding support for ament_cmake_mypy. Build completed without errors.
Because I currently don't have other OSes, so I'm only adding support for arm64 Macs.
=> feat: add package support for ament_cmake_mypy

.github/workflows/testpr.yml, patch/ros-humble-ffmpeg-encoder-decoder.patch
As we introduced several modifications in 2025, such as the use of rosdistro snapshot instead of always building the latest rosdistro, and the use of `pkg_additional_info.yaml` to bump the build number of packages that we want to rebuild, the check for `vinca_*.yaml` modification before running PR does not make a lot of sense. If a PR is not triggering the build of new packages, then the build step is super fast, and if instead a new recipe is triggered without us being aware of this, it is important that the PR CI catches the unintentional package generation.
=> Remove check for .yaml modification before recipe generated in testpr CI job and fix testpr job

patch/dependencies.yaml, patch/ros-humble-openvdb-vendor.patch, patch/ros-humble-spatio-temporal-voxel-layer.patch, vinca_linux_64.yaml, vinca_linux_aarch64.yaml
=> Add spatio_temporal_voxel_layer

vinca_linux_aarch64.yaml
While pulling in `nav2-bringup` to some pixi config I saw it's missing only for aarch64 so this adds it in Ref - https://robostack.github.io/humble.html
=> Added nav2-bringup for aarch64 which was missing

.scripts/build_unix.sh
Currently, the CI is failing due to the additional recipes added for emscripten, which are skipped by rattler-build, resulting in the CI failing due to having an empty output folder.
This pr is a hotfix to check first if anything was built before attempting to upload it, this will effectively fix https://github.com/RoboStack/ros-humble/actions/runs/14767448589 
A better approach would be to check in vinca generate_gha to implement a parse skip, in https://github.com/RoboStack/vinca/blob/9eb0b36b3cb673f6ab0789dd22f06668ccae5fd3/vinca/generate_gha.py#L197 , but I couldn't find the whole list of possible names for the platforms that rattler-build takes
=> CI Hotfix when none packages where built

check_patches_clean_apply.py, patch/dependencies.yaml
In https://github.com/RoboStack/ros-jazzy/pull/95 I aligned the ros-jazzy files with ros-humble, but there were some (minor) fixes that it made sense to propagate from ros-jazzy to ros-humble instead.
=> Align with ros-jazzy

patch/ros-humble-imu-complementary-filter.patch, vinca.yaml
Fixes Windows-specific compilation issues
=> Add patch for imu_tools package

patch/dependencies.yaml, patch/ros-humble-libfranka.patch, vinca.yaml
According to https://github.com/garylvov/pixidock_template this may be useful, let's see if it is tricky to package.
fyi @garylvov
=> Add franka_ros2 package on Linux

robostack.yaml, vinca.yaml
I just found out we ere missing those in https://github.com/Sooner-Rover-Team/auto_ros2/pull/119/files#r2282899688, but it should be easy to compile them.
=> Add ign-ros2-control and gz-ros2-control on non-Windows platforms

vinca.yaml
Only caveat: if one using this package, the gz related env variable should be properly set
```bash
export IGN_GAZEBO_SYSTEM_PLUGIN_PATH=$CONDA_PREFIX/lib
export LD_LIBRARY_PATH=$CONDA_PREFIX/lib:$LD_LIBRARY_PATH
```
before doing `ros2 launch ur_simulation_gz ur_sim_control.launch.py`
Not sure if (and how) I should automate that to be frank. Maybe patching the python launch script ? Let me know, thanks !
=> added ur_simulation_gz

patch/ros-humble-gz-ros2-control.patch, vinca.yaml
This deals with https://github.com/RoboStack/ros-humble/pull/343#issuecomment-3271126846 and extend https://github.com/RoboStack/ros-humble/pull/344 to macOS
=> build `gz-ros2-control` both on Linux and macOS
